### ISSUE TITLE
Client's get_google_devices_json method returns list

### ISSUE THREAD

**Issue by leikoilja** [leikoilja/glocaltokens#14]
**Describe the bug**
Method that is described as `json` returns a list of devices.
See https://github.com/leikoilja/glocaltokens/blob/master/glocaltokens/client.py
```python
    def get_google_devices_json(self):
        """
        Returns a json of google devices with their
        local authentication tokens
        """

        def extract_devices(items):
            """
            Replacement for jq
            """
            devices = []
            for item in items:
                if item.local_auth_token != "":
                    device = {
                        'deviceName': item.device_name,
                        'localAuthToken': item.local_auth_token,
                    }
                    devices.append(device)
            return devices

        homegraph = self.get_homegraph()

        devices = extract_devices(homegraph.home.devices)

        return devices
```

**Expected behavior**
We should either return a json or a list. If former, then we should rename the method and announce a breaking change.

**Comment by ArnyminerZ** [comment]
Implemented it in 7e1cefb and b35a8b5, but not sure why GitHub keeps adding all the commits that I have made, and not just the ones in that branch, will create a new pull request if that's not an issue, but not sure why it's happenning.

**Comment by leikoilja** [comment]
Oh, that's nice, thanks @ArnyminerZ! Can you please create a new branch on your fork, then apply two of those commits on that branch and make a new pull request for these changes? Please also reference this ticket in the PR! Thanks 💥

**Comment by leikoilja** [comment]
Closed in https://github.com/leikoilja/glocaltokens/commit/7b591642990635eb99dbc9e967fa1152d0eeb5bf
