### ISSUE TITLE
Support authentication with only master token

### ISSUE THREAD

**Issue by leikoilja** [leikoilja/glocaltokens#168]
**Is your feature request related to a problem? Please describe.**
We should be able to support master token authentication alone for those clients that are not willing to provide their google user and password credentials. See here - https://github.com/leikoilja/ha-google-home/issues/124#issuecomment-921531375

**Describe the solution you'd like**
Feeding just `master_token` to the client should be sufficient for the client's work

**Additional context**
I think we already mostly support this except that we have some extra protective logic that will `return None` and log an error if no login or no password are provided (See https://github.com/leikoilja/glocaltokens/blob/d7b97bc6c8564d302a2d5d472bee72fd837da071/glocaltokens/client.py#L209) 

Requirements: 
- We need to test the functionality works as expected
- We need to make sure we cover the implementation with sufficient unit tests

**Comment by KapJI** [comment]
Apart from the implementation we need some instructions how to get this master token in the first place.

**Comment by KapJI** [comment]
To be honest, I doubt this is really useful. Master token has the same power as login/password and to obtain it, you still need to use your credentials on some service. The real solution here is using separate service account which has access to the Home.
