### ISSUE TITLE
Add typing

### ISSUE THREAD

**Issue by ArnyminerZ** [leikoilja/glocaltokens#17]
**Is your feature request related to a problem? Please describe.**
Modern IDEs use typing to make small errors like typos, or bad types mixing easier with typing. This should be implemented to have a cleaner code, since the variable types would be known.

**Describe the solution you'd like**
Add typing to all the expressions in the library, for example:
```python
def __init__(self, username:str = None, password:str = None):
```

**Comment by leikoilja** [comment]
@ArnyminerZ, thanks for the issue. Do you have an interest to take a lead on this one?

**Comment by ArnyminerZ** [comment]
I will take it ☺️
