### ISSUE TITLE
403 when trying to get master token

### ISSUE THREAD

**Issue by aaronpowell** [leikoilja/glocaltokens#260]
I'm trying to use the HA integration and came across the auth problem (https://github.com/leikoilja/ha-google-home/issues/528) so it was suggested I just try using the raw package.

When I run it with my credentials I get a 403 from the API calls:

```
vscode ➜ /workspaces/tmp-ha-google $ python3 get-token.py 
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): android.clients.google.com:443
DEBUG:urllib3.connectionpool:https://android.clients.google.com:443 "POST /auth HTTP/1.1" 403 None
ERROR:glocaltokens.client:[!] Could not get master token.
[*] Master token None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): android.clients.google.com:443
DEBUG:urllib3.connectionpool:https://android.clients.google.com:443 "POST /auth HTTP/1.1" 403 None
ERROR:glocaltokens.client:[!] Could not get master token.

[*] Access token (lives 1 hour) None

[*] Google devices local authentication tokens
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): android.clients.google.com:443
DEBUG:urllib3.connectionpool:https://android.clients.google.com:443 "POST /auth HTTP/1.1" 403 None
ERROR:glocaltokens.client:[!] Could not get master token.
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): android.clients.google.com:443
DEBUG:urllib3.connectionpool:https://android.clients.google.com:443 "POST /auth HTTP/1.1" 403 None
ERROR:glocaltokens.client:[!] Could not get master token.
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): android.clients.google.com:443
DEBUG:urllib3.connectionpool:https://android.clients.google.com:443 "POST /auth HTTP/1.1" 403 None
ERROR:glocaltokens.client:[!] Could not get master token.
```

The Python script I'm running is off the README for the repo, with the only change being I've put in my username/password.

I've tried with 2FA enabled and an App Password, and I've tried turning off 2FA and using a username/password, both output the same thing.

**Comment by KapJI** [comment]
It seems you're using python 3.10. Can you try with 3.9? Also what versions of `requests` and `urllib3` you have installed (you can find this using `pip freeze`)?

**Comment by aaronpowell** [comment]
Fresh with python 3.9:

```
vscode ➜ /workspaces/tmp-ha-google $ python3 --version
Python 3.9.12
vscode ➜ /workspaces/tmp-ha-google $ pip install glocaltokens
Defaulting to user installation because normal site-packages is not writeable
Collecting glocaltokens
  Downloading glocaltokens-0.6.5-py3-none-any.whl (31 kB)
Collecting requests<3.0.0,>=2.28.0
  Downloading requests-2.28.0-py3-none-any.whl (62 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 62.8/62.8 KB 1.2 MB/s eta 0:00:00
Collecting grpcio<2.0.0,>=1.46.1
  Downloading grpcio-1.47.0-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (4.5 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.5/4.5 MB 8.5 MB/s eta 0:00:00
Collecting zeroconf<0.39.0,>=0.38.7
  Downloading zeroconf-0.38.7-py3-none-any.whl (106 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 106.6/106.6 KB 1.9 MB/s eta 0:00:00
Collecting simplejson<4.0.0,>=3.17.2
  Downloading simplejson-3.17.6-cp39-cp39-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_12_x86_64.manylinux2010_x86_64.whl (136 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 136.6/136.6 KB 11.0 MB/s eta 0:00:00
Collecting gpsoauth<2.0.0,>=1.0.1
  Downloading gpsoauth-1.0.2-py3-none-any.whl (6.6 kB)
Collecting protobuf==3.19.4
  Downloading protobuf-3.19.4-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (1.1 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.1/1.1 MB 7.7 MB/s eta 0:00:00
Collecting pycryptodomex>=3.0
  Downloading pycryptodomex-3.15.0-cp35-abi3-manylinux2010_x86_64.whl (2.3 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.3/2.3 MB 8.2 MB/s eta 0:00:00
Collecting six>=1.5.2
  Downloading six-1.16.0-py2.py3-none-any.whl (11 kB)
Collecting urllib3<1.27,>=1.21.1
  Downloading urllib3-1.26.9-py2.py3-none-any.whl (138 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 139.0/139.0 KB 2.9 MB/s eta 0:00:00
Collecting charset-normalizer~=2.0.0
  Downloading charset_normalizer-2.0.12-py3-none-any.whl (39 kB)
Collecting idna<4,>=2.5
  Downloading idna-3.3-py3-none-any.whl (61 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 61.2/61.2 KB 4.2 MB/s eta 0:00:00
Collecting certifi>=2017.4.17
  Downloading certifi-2022.6.15-py3-none-any.whl (160 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 160.2/160.2 KB 1.6 MB/s eta 0:00:00
Collecting ifaddr>=0.1.7
  Downloading ifaddr-0.2.0-py3-none-any.whl (12 kB)
Installing collected packages: ifaddr, zeroconf, urllib3, six, simplejson, pycryptodomex, protobuf, idna, charset-normalizer, certifi, requests, grpcio, gpsoauth, glocaltokens
Successfully installed certifi-2022.6.15 charset-normalizer-2.0.12 glocaltokens-0.6.5 gpsoauth-1.0.2 grpcio-1.47.0 idna-3.3 ifaddr-0.2.0 protobuf-3.19.4 pycryptodomex-3.15.0 requests-2.28.0 simplejson-3.17.6 six-1.16.0 urllib3-1.26.9 zeroconf-0.38.7
WARNING: You are using pip version 22.0.4; however, version 22.1.2 is available.
You should consider upgrading via the '/usr/local/bin/python -m pip install --upgrade pip' command.
vscode ➜ /workspaces/tmp-ha-google $ python3 get-token.py 
ERROR:glocaltokens.client:[!] Could not get master token.
[*] Master token None
ERROR:glocaltokens.client:[!] Could not get master token.

[*] Access token (lives 1 hour) None

[*] Google devices local authentication tokens
ERROR:glocaltokens.client:[!] Could not get master token.
ERROR:glocaltokens.client:[!] Could not get master token.
ERROR:glocaltokens.client:[!] Could not get master token.
```

Here's the packages:

```
vscode ➜ /workspaces/tmp-ha-google $ pip freeze
certifi==2022.6.15
charset-normalizer==2.0.12
glocaltokens==0.6.5
gpsoauth==1.0.2
grpcio==1.47.0
idna==3.3
ifaddr==0.2.0
protobuf==3.19.4
pycryptodomex==3.15.0
requests==2.28.0
simplejson==3.17.6
six==1.16.0
urllib3==1.26.9
zeroconf==0.38.7
```

**Comment by leikoilja** [comment]
@aaronpowell, seems like you are getting hit by 403 (permission denied) error, a bit of a silly question, but better safe then sorry: are you sure you credentials are valid? And when running `get_tokens` example, you are using just a username `user` in the example of `user@gmail.com`, not the full email address, right?

**Comment by leikoilja** [comment]
@aaronpowell to completely resemble out test setup with dependencies can you please install using `poetry` as described in [contribution docs](https://github.com/leikoilja/glocaltokens/blob/master/CONTRIBUTING.md). Once you have poetry just run `poetry install` from project directory to create managed virtual env and install dependency packages exactly similar to ours. Note, you don't need to manually install `glocaltokens` package in your virtual env, when running the example code

**Comment by aaronpowell** [comment]
> @aaronpowell, seems like you are getting hit by 403 (permission denied) error, a bit of a silly question, but better safe then sorry: are you sure you credentials are valid? And when running `get_tokens` example, you are using just a username `user` in the example of `user@gmail.com`, not the full email address, right?

I'm not using a gmail account for this Google account, I'm using a custom domain that I've created a Google account with. I know the creds are valid as I can login via the browser with them.

**Comment by aaronpowell** [comment]
> @aaronpowell to completely resemble out test setup with dependencies can you please install using `poetry` as described in [contribution docs](https://github.com/leikoilja/glocaltokens/blob/master/CONTRIBUTING.md). Once you have poetry just run `poetry install` from project directory to create managed virtual env and install dependency packages exactly similar to ours. Note, you don't need to manually install `glocaltokens` package in your virtual env, when running the example code

Do I need to clone the `glocaltokens` repo and set it up there?

**Comment by KapJI** [comment]
> I'm using a custom domain that I've created a Google account with.

Well, that's something. Can you try to create new google account and check if you can get master token for it? Basically you need to find any setup when it works so then you can triage the issue. It can be different machine, OS, network region, password length, etc. Then you can change one variable a time back to find what causes this.

> Do I need to clone the glocaltokens repo and set it up there?

Yes, clone the repo, install Poetry (`pip install poetry` should be enough) and run `poetry install`. You can prepend commands with `poetry run` to use its virtualenv, e.g. `poetry run python get-token.py`

**Comment by aaronpowell** [comment]
> > I'm using a custom domain that I've created a Google account with.
> 
> Well, that's something. Can you try to create new regular gmail account and check if you can get master token for it? Basically you need to find any setup when it works so then you can triage the issue. It can be different machine, OS, network region, password length, etc. Then you can change one variable a time back to find what causes this.

Do you want that added to the Google Home, or go 100% clean?

**Comment by KapJI** [comment]
It doesn't matter, getting that master token only provides access to account itself, so it should work in all cases. But you can try both.

**Comment by aaronpowell** [comment]
Dug up an old gmail account of mine and am able to get the master token for it. Can't add it to the Google Home (need to setup a phone linked to that account).

So I tried my wife's gmail account (which is in the Google Home) and it fails with the same reason my (non-gmail) account fails.

I'll try setting up poetry now.

**Comment by aaronpowell** [comment]
```
vscode ➜ ~/glocaltokens/glocaltokens (master) $ poetry run python /workspaces/tmp-ha-google/get-token.py 
ERROR:glocaltokens.client:[!] Could not get master token.
[*] Master token None
ERROR:glocaltokens.client:[!] Could not get master token.

[*] Access token (lives 1 hour) None

[*] Google devices local authentication tokens
ERROR:glocaltokens.client:[!] Could not get master token.
ERROR:glocaltokens.client:[!] Could not get master token.
ERROR:glocaltokens.client:[!] Could not get master token.
```

**Comment by KapJI** [comment]
That's some progress! So now you need to find what makes these accounts different.

Btw, I also have personal google account on dedicated domain. But I use separate gmail account which only has access to Google Home for this integration to not expose my personal account. Although I can still get master token for my personal account just fine both on Linux and Mac. It has 2fac enabled and I use app password.

**Comment by aaronpowell** [comment]
My primary Google account is created with Google Apps and that causes a WORLD of problems with Google Home, so this one have a dedicated account, but under my domain.

The email address has a `+` in it, the one that owns the home.

**Comment by aaronpowell** [comment]
> The email address has a `+` in it, the one that owns the home.

I wonder if that's the problem. I just tried with my primary Google account (which is on the same custom domain) and it was able to retrieve the token.

Because it's on Google Apps I can't add it to this Google Home, so I'll try a non-`+` email.

**Comment by KapJI** [comment]
Yep, that's a possible explanation.

**Comment by KapJI** [comment]
This explains how to get extra logging from `requests`:
https://stackoverflow.com/questions/16337511/log-all-requests-from-the-python-requests-module

Fetching of master token is implemented here, you can probably modify that code and use `gpsoauth` directly (it also uses `poetry`):
https://github.com/simon-weber/gpsoauth/blob/master/gpsoauth/__init__.py#L91-L143

**Comment by KapJI** [comment]
This is simple example of using `gpsoauth`:
```python3
from gpsoauth import perform_master_login

login = "login@domain.com"
password = "app_password"


response = perform_master_login(login, password, "aabbccddeeff1122")
print("Response:", response)
print("Master token:", response["Token"])
```

**Comment by KapJI** [comment]
Well, I remember that `+` is actually very special in email account. Basically if your account is `login+smth@gmail.com` then your actual account is `login@gmail.com` and `smth` will be ignored but can be used for adding labels on email, sorting them by folders, etc.

**Comment by aaronpowell** [comment]
Yeah, I know that `+` is special, it was mostly me being lazy about setting up the account, rather than creating a full mailbox.

```
vscode ➜ /workspaces/tmp-ha-google $ python basic.py 
Response: {'Error': 'UNKNOWN_ERR'}
Traceback (most recent call last):
  File "/workspaces/tmp-ha-google/basic.py", line 8, in <module>
    print("Master token:", response["Token"])
KeyError: 'Token'
```

That's from the new script.

I'll create a complete mailbox and add it tomorrow then report back.

**Comment by KapJI** [comment]
Have you tried using only actual part of the login? You shouldn't pass part with `+`. Basically it should be `login@domain.com` instead of `login+label@domain.com`.

**Comment by KapJI** [comment]
@aaronpowell did you have change to try login without `+` part?

**Comment by aaronpowell** [comment]
The non-`+` email is attached to a different Google Account, but it does work (meaning that a custom domain with Google Accounts is valid).

I'll try setting up yet another email and Google Account and add it to the home.

**Comment by KapJI** [comment]
You don't have any accounts with `+`, they are different addresses which are delivered to the same account. To use it, you should strip part after `+` from login.

**Comment by aaronpowell** [comment]
Stripping the `+` didn't do anything (going from `me+googlehome@...` to `megooglehome@...`) as the `+` really only impacts on my mail provider end.

But I did create a new Google account (`homeassistant@...`), attempted to get the token before adding it to the Home - that worked.

I then added it to the Home and ran the script again - it **still** worked, _and_ it's listing the Google Nest devices!

I'll rerun the tests again later today to ensure there was no fluke caching happening, but it might be something to do with the way `+`-based email addresses are handled.

**Comment by KapJI** [comment]
It should be just `me@...`, not `me+googlehome@...` or `megooglehome@...`.

**Comment by aaronpowell** [comment]
> It should be just `me@...`, not `me+googlehome@...` or `megooglehome@...`.

Not quite - I have a Google Account that uses the email `me@...` which is linked to a legacy Google Apps instance, so is technically a _work_ account as far as Google is concerned. That account can't be used with Google Home properly (it can own a Home but you can't add anyone else to the Home, which is a major limiting factor for family use), so I created an alias'ed email using `me+googlehome@...` which then has its own Google Account.

Either can be logged into, one has all my YouTube history, my Google search history, basically everything that Google knows about me, the other is really just for use with Google Home, sure, it _could_ have YouTube history (and, well, it does thanks to watching YouTube on Google TV), but they are completely separate identities as far as Google is concerned.

Now maybe that's the problem, the auth process is mistakenly handling the `+...` segment of the email badly, but it's still a completely valid email (just like using `{`, `}`, `|`, `#`, and a bunch of other symbols in the local part). It's then up to the mail server to decide how to handle it. Gmail popularised using `+` to "tag" emails (Gmail calls it "task oriented email" and Exchange Online calls is "plus addressing"), but you could have an email where that is just part of it, and not doing something special at the mail server to redirect to a certain inbox.

To illustrate, I tested with `me@...` (which isn't part of the Google Home, but the plus address is) and it gets a master token, so ✅, but it does **not** get the Google Home/Nest devices in the Home, so ❌.

If I then try with the new, non-`+` `homeassistant@...` address (which is part of the Google Home), I can get the master token, so ✅, and it does get the list of Google Home/Nest devices in the Home, so ✅ again.

Ultimately, I think I have a super weird edge case that's probably more of a problem at Google's any than anything, and given the obscurity of it, they probably won't fix it, but I do feel like #270 might result in some false positives.

**Comment by KapJI** [comment]
So if I understand you correctly you have Google account `me+googlehome@...` which is registered to non-google email address? Surprisingly that seems possible, otherwise I don't see how to achieve this.

Because G Suite doesn't allow to create such account:
![Screenshot 2022-07-05 at 14 12 34](https://user-images.githubusercontent.com/3767331/177335867-c7778aa6-1e88-402e-afd4-94fcc9023237.png)

When I try to add `+test` to my existing account in the login form, it says account doesn't exist:
![Screenshot 2022-07-05 at 14 20 44](https://user-images.githubusercontent.com/3767331/177337483-c0b0568e-1349-406d-91ac-575472ae6bb7.png)

**Comment by KapJI** [comment]
Awesome!
