### ISSUE TITLE
Warning when not using HA-zeroconf

### ISSUE THREAD

**Issue by DurgNomis-drol** [leikoilja/glocaltokens#27]
**Describe the bug**

`2021-02-16 16:54:24 WARNING (SyncWorker_1) [homeassistant.helpers.frame] Detected integration that attempted to create another Zeroconf instance. Please use the shared Zeroconf via await homeassistant.components.zeroconf.async_get_instance(hass). Please report issue to the custom component author for ha-glocaltokens using this method at custom_components/ha-glocaltokens/api.py, line 74: devices = json.loads(self._client.get_google_devices_json())`

**Comment by leikoilja** [comment]
Yeh, i believe that's what I was thinking of when discussing `zeroconf` in https://github.com/leikoilja/ha-glocaltokens/issues/18#issuecomment-779601977.
@ArnyminerZ, what do you think about it?

**Comment by ArnyminerZ** [comment]
It's still a warning, so at least it's not breaking. Anyway, this should be fixed. Maybe some kind of disabler for `zeroconf` at `glocaltokens` when using HA?

**Comment by DurgNomis-drol** [comment]
Sounds right to me, but that is over my skill level 😉

**Comment by leikoilja** [comment]
@ArnyminerZ, I was thinking of the same, but I am afraid it might be detecting it through a dependency list like this:
ha-glocaltokens relies on glocaltokens, which in it's requirements has zeroconf. If this stands true, we might not be able to simply disable it.

Thou, checking the warning message again, maybe I am wrong, perhaps it detects zeroconf instance registration and if so, then we can make it optional and disable `zeroconf` at `glocaltokens` when using HA as you have suggested, @ArnyminerZ.

**Comment by ArnyminerZ** [comment]
Yeah, not sure, haven't seen that warning since `ha-localtokens` is still not working for me 😀 
Once I have it working I will start researching about it.

**Comment by DurgNomis-drol** [comment]
It wont work until this [Patch](https://github.com/leikoilja/ha-glocaltokens/pull/33) have been merged. Please open an issue over at `ha-glocaltokens`

**Comment by DurgNomis-drol** [comment]
See [here](https://github.com/leikoilja/glocaltokens/issues/28#issuecomment-781466485)

**Comment by DurgNomis-drol** [comment]
[Here](https://github.com/home-assistant/core/tree/dev/homeassistant/components/zeroconf) is what we should use instead. Do you wanna take a look @ArnyminerZ  at it and then we can work togther to make it work with HA? Maybe pass boolean or something to glocaltokens?

**Comment by ArnyminerZ** [comment]
I will take a look at it once I finish my current PR at `glocaltokens`

**Comment by leikoilja** [comment]
@DurgNomis-drol, we already have a boolean in `glocaltokens`. I will create a PR in `ha-glocaltokens` to not use autodiscovery for now, so we could implement `zeroconf` on HA side

**Comment by ArnyminerZ** [comment]
Yeah, the discovery right now can be disabled through `disable_discovery=True`, but still it might be inconvenient to keep importing the library. I was thinking maybe something like an environment variable which disabled `zeroconf` completely?

**Comment by leikoilja** [comment]
@ArnyminerZ we could do so, but it might be confusing for some ppl. I have seen conditional python importing, we can simply use that as well i guess, can we not?
Like 
```python
if disable_discovery is False:
  import zefoconf
  ...
```

**Comment by ArnyminerZ** [comment]
Yeah, that was what I was thinking about, but where do we get that `disable_discovery` should we import `zeroconf` from inside the function? That was what I was meaning with the environment variables.

**Comment by leikoilja** [comment]
disable_discovery is going to come from HA integration, isnt it? Something like `devices = client.get_google_devices(disable_discovery=True)`. And then `zeroconf` is imported inside the function (as mentioned above)

**Comment by ArnyminerZ** [comment]
Ok, I guess that should work, will try to implement it today.
