### ISSUE TITLE
Implement access token error handling

### ISSUE THREAD

**Issue by leikoilja** [leikoilja/glocaltokens#3]
**Is your feature request related to a problem? Please describe.**
The access token is changed every ~1h. It is currently stored locally. So if the client hangs for a few hours locally storred access token will not be valid anymore

**Describe the solution you'd like**
Implement error handling when the access token is incorrect to retry by the first refreshing access token using master token.

**Comment by ArnyminerZ** [comment]
Check #9, I've added time expiration check, maybe error handling should also be done.

**Comment by leikoilja** [comment]
Thank you, @ArnyminerZ, I think what you have implemented in #9 is amazing and is the first move towards the more robust package. Let's revisit this later if the problem persists.
