### ISSUE TITLE
[aiohttp.server] Error handling request

### ISSUE THREAD

**Issue by ollioddi** [leikoilja/glocaltokens#35]
Fantastic work guys!

I have tried installing the latest version and it went fine on hacs until i tried to enter my app password.

Since i'm using 2fa, i need to use the app password. When entering and saving, the following error is displayed.

Any suggestions on what i can do to fix?

> 2021-03-02 11:37:48 WARNING (MainThread) [homeassistant.util.async_] Detected I/O inside the event loop. This is causing stability issues. Please report issue to the custom component author for glocaltokens doing I/O at custom_components/glocaltokens/api.py, line 36: master_token = self._client.get_master_token()
2021-03-02 11:37:48 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
File "/usr/local/lib/python3.8/site-packages/aiohttp/web_protocol.py", line 422, in _handle_request
resp = await self._request_handler(request)
File "/usr/local/lib/python3.8/site-packages/aiohttp/web_app.py", line 499, in _handle
resp = await handler(request)
File "/usr/local/lib/python3.8/site-packages/aiohttp/web_middlewares.py", line 118, in impl
return await handler(request)
File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 56, in security_filter_middleware
return await handler(request)
File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 18, in request_context_middleware
return await handler(request)
File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 72, in ban_middleware
return await handler(request)
File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 127, in auth_middleware
return await handler(request)
File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 129, in handle
result = await result
File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 169, in post
return await super().post(request, flow_id)
File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 60, in wrapper
result = await method(view, request, *args, **kwargs)
File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 106, in post
result = await self._flow_mgr.async_configure(flow_id, data)
File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 155, in async_configure
result = await self._async_handle_step(flow, cur_step["step_id"], user_input)
File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 213, in _async_handle_step
result: Dict = await getattr(flow, method)(user_input)
File "/config/custom_components/glocaltokens/config_flow.py", line 46, in async_step_user
CONF_ANDROID_ID: client.get_android_id(),
File "/config/custom_components/glocaltokens/api.py", line 48, in get_android_id
return self._client._get_android_id()
AttributeError: 'GLocalAuthenticationTokens' object has no attribute '_get_android_id'

**Comment by DurgNomis-drol** [comment]
Have you updated both glocaltokens and ha-google home to latest version? 

This is still a beta, maybe alpha, and it is not ready for primetime yet, but will be very soon 😊

**Comment by ollioddi** [comment]
@DurgNomis-drol I added https://github.com/leikoilja/ha-google-home as a repository in HACS. Shouldnt this be the latest version?

And yes, i realize it is in very early stages but i would like to help test it, fully aware that there is bugs.

**Comment by DurgNomis-drol** [comment]
@leikoilja Is the HACS repository updated to the newest version?

Right now, it doesn't not work correctly because of a bug with zeroconf we haven't fixed yet

But we are glad that you want to test it and try it out 😊

**Comment by leikoilja** [comment]
Hey hey, gentlemen.

When adding to HACS as custom repo you can select the version. If you select 'master' it will be the latest version we are working on.
Unfortunately there is a lot more to do before 'master' even works. It's broken right now, but I m working on it and once the 'master' is fixed, we ll keep it as a bare minimum working, having all development in 'dev' branch.

Just a few more days 🤩💥👊 I ll ping you both 💥

**Comment by ollioddi** [comment]
Awesome!

Thats what i thought, i tried both versions but as you say, the master is broken at the momemt.

I am keeping my eye on the project :)

This really is fantastic work! Wish i could contribute but it is far beyond my knowledge

**Comment by leikoilja** [comment]
You can always join, once you are up for a challenge, @ollioddi 💥 We have some smaller tasks like writing unit tests that might be interesting. It's not very straight forward, because it should follow HA flow and testing patterns, but a good think is that there are dozens of similar integration where unit testing is already done and we can almost copy/paste refactoring and fitting to our integration :)

**Comment by DurgNomis-drol** [comment]
@ollioddi  We are ready for you to test it if you are up for the task 😄

**Comment by leikoilja** [comment]
Gentlemen, i ll close this issue, cause it's not an issue anymore 😄 
@ollioddi, please check https://github.com/leikoilja/ha-google-home for some early testings 💥

**Comment by ollioddi** [comment]
Hi @leikoilja that sounds amazing.

I am unfortunately still experiencing this issue as mentioned above. Any idea as to why this error occurs?

It should be mentioned that i have recently had network issues with HA reaching my google devices. It should be fixed and i can control them from HA without issues. It just seems like a network error.

**Comment by DurgNomis-drol** [comment]
@ollioddi Make sure that you are using the latest master. It says it cannot find _get_android_id. That is because it was renamed some time ago in glocaltokens. Make sure that glocaltokens is updated to the latest version. 

I have had problems with HA not updating dependencies for custom components before(I don't know why). You can check what version of glocaltokens you have installed by running `pip show glocaltokens` 😄 

Hope this helps

**Comment by leikoilja** [comment]
@ollioddi just as @DurgNomis-drol  has a mentioned, suggest you delete the integration you have installed now and the follow README file to reinstall it selecting 'Master' version. 

Try it out and keep us updated :)

**Comment by ollioddi** [comment]
HI @leikoilja it worked uninstalling it and installing again.

I had already done this multiple times and completely re-added in HACS so i dont know exactly why it didn't work earlier. I can now successfully see one of my devices which is amazing.

I have another device, a Lenovo Smart Clock which is not auto discovered for some reason. Is there a way to manually add? It has a static ip address.

**Comment by leikoilja** [comment]
@DurgNomis-drol has just did some amazing job adding lenovo smart clock support at https://github.com/leikoilja/ha-google-home/pull/70

**Comment by ollioddi** [comment]
Awesome guys. No inconvenience at all, just really happy to see this taking shape.

Thanks @DurgNomis-drol for adding the clock! Greatly appreciated.

**Comment by DurgNomis-drol** [comment]
@ollioddi No problem! 😄 

Good to hear it works!
