### ISSUE TITLE
Authentication error after ~22h of usage

### ISSUE THREAD

**Issue by leikoilja** [leikoilja/glocaltokens#36]
**Describe the bug**
Left the `Google Home` HA integration for 24h and after the time has passed I have discovered that integration fails to fetch data due to authentication error.
![image](https://user-images.githubusercontent.com/10655107/110073161-35b05800-7d7f-11eb-9fba-d15e950d73b8.png)

While this should not happen and tokens must be automatically refreshed by `glocaltokens` library. I am afraid it might not be working... OR we might need to shorten the access token and homegraph durations. @ArnyminerZ, do you have any thoughts?

**Comment by leikoilja** [comment]
And fully restarting my host(RPi) has force refreshed tokens and it all makes smooth after

**Comment by DurgNomis-drol** [comment]
I can confirm the same problem, but it happened for me only about 11 hours later. At about 3.20 (am) at night

**Comment by leikoilja** [comment]
Good, happy I', not the only one 😄 @DurgNomis-drol, how did you figure out it happened about 3.20am? 
I am wondering if the token is expiring **after** a certain time or **at** a certain time. Like it lives 24h for example or it expires at 3am everyday sort of thing 😄 🤔

**Comment by DurgNomis-drol** [comment]
I check HA logs and could see that the error `Failed to fetch Køkken data, API returned 401: <ClientResponse(https://192.168.0.205:8443/setup/assistant/alarms) [401 Unauthorized]> <CIMultiDictProxy('Access-Control-Allow-Headers': 'Content-Type', 'Cache-Control': 'no-cache', 'Content-Length': '0')>` first occurred at that time. 

My guess is it is at a more or less specific time every night

Could we just do something like, if 401 then call function that gets a new local_auth_token and then retry with a limit on retries? 😁

**Comment by leikoilja** [comment]
I was thinking of the same, @DurgNomis-drol, but in theory, it should not be `ha-google-home`'s task to care about tokens and authentication. I think we need to adjust `glocaltokens` to fetch tokens in a proper manner/timing to eliminate the issue. And only then, as extra precautions, we can add logic to `ha-google-home` to force reload tokens if 401 response is got :)

**Comment by DurgNomis-drol** [comment]
I agree, fixing it in `glocaltokens` will also fix it for other applications that uses it. :)

**Comment by ArnyminerZ** [comment]
The issue here is that we don't really know for how much time are the tokens valid, or even if it's a fixed amount of time, o they get invalidated once a day at a specific time.
The thing with time validation was a temporal patch, for waiting until the error, and catching it, for generating a new one. I can try to work with this now

**Comment by DurgNomis-drol** [comment]
From [https://rithvikvibhu.github.io/GHLocalApi/](https://rithvikvibhu.github.io/GHLocalApi/#section/Google-Home-Local-API/Getting-Started)

```text
## Local Authorization Token
This token must be sent in all requests in the header cast-local-authorization-token. It is short-lived (~1 day) and may change unexpectedly (with a sync, change in homegraph, etc.)
```

I think it is the last thing that gets us. We should as @ArnyminerZ describes it, catch the error when it happens as google does not include a `token expires ` attribute when getting the local auth token from homegraph

**Comment by ArnyminerZ** [comment]
Yeah, got that 1 day duration from there, but it's said there aprox 1 day, so I was not so confident about it. It was just a matter of time that it fails. I'm taking a look at error handling for grpc.

**Comment by DurgNomis-drol** [comment]
Should we test if the token works before passing it on in `glocaltokens`?

**Comment by ArnyminerZ** [comment]
Found [this](https://stackoverflow.com/a/64578855/5717211). Maybe we can just:
```python3
def get_homegraph(self):
    ...
    try:
        response = rpc_service.GetHomeGraph(request)
        self.homegraph = response
    except grpc.RpcError as rpc_error:
        if rpc_error.code() == 401:
            # TODO: Get a new token and rerun get_homegraph
            pass
        else:
            print(f"Received unknown RPC error: code={rpc_error.code()} message={rpc_error.details()}")
    ...
```

**Comment by leikoilja** [comment]
That's brilliant, @ArnyminerZ! 👍  Thanks for picking it up 💥

**Comment by DurgNomis-drol** [comment]
Maybe i'm not understanding this correctly but the error occurs in ha-google-home when it tries to fetch the data from the device. And this wont help with that unless we change something in ha-google-home to make it retrieve a new token.

As far as i know, grpc does not throw an error, because it does not know that the tokens is not valid

Please correct me if i'm wrong

**Comment by ArnyminerZ** [comment]
It does indeed return an error, the [401 http error](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/401). This error is returned by the server, who does know that the token is not valid, so it doesn't send us any data. That's what we have to handle.

**Comment by DurgNomis-drol** [comment]
The request to the end device is not made through grpc but using a requests module and a simple GET request? (In ha-google-home) And yes there it returns 401 if it is not valid

**Comment by leikoilja** [comment]
uuu, I actually don't know who is returning 401 for us. 🤔  
It might be call to `grpc`(in glocaltokens) or `session.get`(in ha-google-home). 
But either way i think we should have a check for both 😄

**Comment by DurgNomis-drol** [comment]
See my edit above and i agree with @leikoilja that we should make sure that we also handle it in `ha-google-home`

**Comment by ArnyminerZ** [comment]
Ok, now I've got it done well. I made a mess with unpushed commits 😅

**Comment by leikoilja** [comment]
Consider scenario: 
- We call `GetHomeGraph` - it returns valid object that we "cache" for 24h. 
- We extract our google devices (with local auth tokens) from homegraph and populate with IP addresses through zeroconf
- We give out that data to ha-google-home
- ha-google-home makes API call using those local auth tokens coming all the way from "cached" homegraph
- Google Home might return 401 because some of the local auth tokens taken from homegraph are expired

So i think what you are fixing is a problem we have not even considered yet - if cached access token is expired.

But what we probs need to do to solve this issue is introduce `force_reload_homegraph` parameter to `get_google_devices`, which with set `self.homegraph = None`.
And on `ha-google-home` when we do API calls we catch 401 errors and then re-fetch all devices(and their tokens correspondingly) by calling `glocaltokens.get_google_devices(... force_reload_homegraph=True)` which will reload homegraph and return updated devices with new local auth tokens.

I don't know if i understand it right or am getting confused myself 😄

**Comment by DurgNomis-drol** [comment]
Homegraph will always contain the correct local_auth_token, so @ArnyminerZ fix should fix it for now. I was just  getting confused about it. But there may be other bugs we have not consider yet 😄

**Comment by leikoilja** [comment]
Hmmm, not sooo sure about it...
1. We call to get `get_google_devices` in ha-google-home
2. It fetches homegraph - all good and up to date at this point. But after fetching it we "cache" it in `self.homegraph = response` for 24h (See [here](https://github.com/leikoilja/glocaltokens/blob/e8642ac2812749681262dc6cc6ca6b40f1952099/glocaltokens/client.py#L207))
3. So within the next 24 hours every time `ha-google-home` is calling `get_google_devices` it will get until `get_homegraph` and give false positive here:
```python 
        if self.homegraph is None or self._has_expired(
            self.homegraph_date, HOMEGRAPH_DURATION
        ):
```
because `self.homegraph` already exists and our 24h HOMEGRAPH_DURATION is not yet expired.

So if the local auth token actually expires during those 24h our cached `homegraph` is not updated until 24h expires and the check allows it to do a new request.

Am i getting it wrong? 🤔

**Comment by DurgNomis-drol** [comment]
No you are right about that, it should probably just be removed, same with:

```python
...
def get_access_token(self) -> Optional[str]:
        if self.access_token is None or self._has_expired(
            self.access_token_date, ACCESS_TOKEN_DURATION
        ):
           ...
```

**Comment by leikoilja** [comment]
No no, i think both of them are great to be there, otherwise we would spam google servers everytime we need data. I think what @ArnyminerZ has just implemented in #37 is catering for when access token is old, but our ACCESS_TOKEN_DURATION is too long. 
I propose we:
- Keep the time checks - "caching"
- Add `force_homegraph_reload` which will bypass timecheck for homegraph
- Decrease our caching timeouts half? 
- Implement reloading of homegraph on `ha-google-home`.

@ArnyminerZ what do you think about it all? :D

**Comment by ArnyminerZ** [comment]
Yeah, implementing `force_homegraph_reload` could be a smart feature.
Reducing the timeouts is just adjusting a constant, so it wouldn't be an issue. But still, the hypothesis that the reload takes places at a specific time is still there or has been discarded?

**Comment by ArnyminerZ** [comment]
Added to #37 both `invalidate_access_token` and `invalidate_homegraph`. They just reset the "cache" of the token and data, and invalidates the last update variable. This should be enough, simply the next time a fetch is tried, it would be like it's the first time.

**Comment by leikoilja** [comment]
To be honest, i have never seen tokens being invalidated at a specific time in the day. All the tokens I have worked with are all time-issued for a certain time. I believe we should still have it in the back of our minds, but it would be very hard to find that time when it resets them. Thank you for awesome invalidate methods, @ArnyminerZ. If you agree, let's add `force_homegraph_reload` argument (default to False) to our `get_google_device` method that we can use from `ha-google-home` :)

**Comment by ArnyminerZ** [comment]
Take a look at it in #37 😉
