### ISSUE TITLE
Unable to install v0.2.4 on Windows but v0.2.3 works

### ISSUE THREAD

**Issue by samapriya** [leikoilja/glocaltokens#40]
**Windows 10 Installation issue**
While I am able to install and use glocaltokens==0.2.3 on my machine v 0.2.4 is giving me the following error.

Setup details:
**Python 3.8.6 (tags/v3.8.6:db45529, Sep 23 2020, 15:52:53) [MSC v.1927 64 bit (AMD64)] on win32**

```
    ERROR: Command errored out with exit status 1:
     command: 'c:\pythonenv\venv3\scripts\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\samapriya\\AppData\\Local\\Temp\\pip-install-e9v3zubr\\glocaltokens\\setup.py'"'"'; __file__='"'"'C:\\Users\\samapriya\\AppData\\Local\\Temp\\pip-install-e9v3zubr\\glocaltokens\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base pip-egg-info
         cwd: C:\Users\samapriya\AppData\Local\Temp\pip-install-e9v3zubr\glocaltokens\
    Complete output (7 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\samapriya\AppData\Local\Temp\pip-install-e9v3zubr\glocaltokens\setup.py", line 7, in <module>
        HISTORY = history_file.read()
      File "C:\Program Files\Python38\lib\encodings\cp1252.py", line 23, in decode
        return codecs.charmap_decode(input,self.errors,decoding_table)[0]
    UnicodeDecodeError: 'charmap' codec can't decode byte 0x90 in position 107: character maps to <undefined>
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```
I was able to install pycryptodomex based on instructions on their page and I am running v0.2.3 in the meantime.

**Comment by DurgNomis-drol** [comment]
What is your installation method for Windows? VM?

**Comment by DurgNomis-drol** [comment]
@leikoilja It seems to relate to this problem [here](https://stackoverflow.com/a/9233174)

**Comment by leikoilja** [comment]
Ou.... that's a very particular issue 🤔   
I currently only have mac os / Linux to play with, but would any of you guys @samapriya or @DurgNomis-drol be interested in digging a bit more how we can read from the HISTORY file having it encoding compatible? 

```bash
glocaltokens\setup.py", line 7, in <module>
        HISTORY = history_file.read()
```

**Comment by DurgNomis-drol** [comment]
@leikoilja Is the HISTORY.md file encoded in `utf8`?

**Comment by KapJI** [comment]
@DurgNomis-drol yes, it has emojis :)

**Comment by DurgNomis-drol** [comment]
@KapJI Ah thanks, didn't know that 😄 

A simple fix would be this:

```python
with open("README.md", encoding="utf8") as readme_file:
    README = readme_file.read()

with open("HISTORY.md", encoding="utf8") as history_file:
    HISTORY = history_file.read()
```

**Comment by KapJI** [comment]
@leikoilja btw, history is also missing some recent versions

**Comment by leikoilja** [comment]
I m wondering if it's even worth keeping. Does anyone know how to omit it reusing release notes instead on pypi? 😅🤷‍♂️🤔
The history file seems only to be used in pypi, so if it's possible to drop it, we should do it 😅

**Comment by DurgNomis-drol** [comment]
I will just wait to open a PR if you decide to just delete it 😄

**Comment by samapriya** [comment]
Thank you all I love the community support here, also wondering if a CI using github workflows would be useful to check for different OS and python versions. @leikoilja  Adding a gist here
https://gist.github.com/samapriya/1c3256629597251e2ca2efabfea35280

@leikoilja I am using this for a [Google Home tool here](https://github.com/samapriya/ghome), for now I fixed the requirements to be 0.2.3. Happy Monday everyone

**Comment by leikoilja** [comment]
That sounds like a great cli tool to come! 💥🤩

@samapriya, that's a great suggestion, feel free to open a PR here with your gist, it will be easier to merge 😂

In a meanwhile I'll do some reading if we need the history file at all and if not, we ll just drop  it :)

**Comment by samapriya** [comment]
Thanks @leikoilja
Created the PR with branck glocaltokens-ci :)

**Comment by KapJI** [comment]
> I m wondering if it's even worth keeping. Does anyone know how to omit it reusing release notes instead on pypi? 😅🤷‍♂️🤔
> The history file seems only to be used in pypi, so if it's possible to drop it, we should do it 😅

I think it can be dropped from pypi and kept only on github releases. Poetry for example doesn't provide instruments to set history for pypi at all. Will be easier to maintain.
