### ISSUE TITLE
Do not initialise Devices with invalid `local_auth_token`

### ISSUE THREAD

**Issue by leikoilja** [leikoilja/glocaltokens#44]
**Describe the bug**
When we get a fresh `homegraph` we iterate through devices creating new instances `Device` [ref](https://github.com/leikoilja/glocaltokens/blob/e6fa89793bc72c84b3b61f99c371fdb6d7ba8c2f/glocaltokens/client.py#L271) for each of discovered devices. In the `Device` initialization `__init__` we do the validation for `local_auth_token`, however, if the validation fails we still return the "half-baked" object back to `devices` that is later used.

** Referece **
See the issue [here](https://github.com/leikoilja/ha-google-home/issues/91)

**To Reproduce**
Put a debugger breakpoint right before token validation and temper with a token. 

**Expected behavior**
If any of the validations fail - skip adding the device

**Comment by leikoilja** [comment]
@ArnyminerZ would you be interested in helping out with this one? :)

**Comment by ArnyminerZ** [comment]
Ok, working on it in 30 mins aprox

**Comment by philippefs35** [comment]
Thank you for your help @leikoilja @ArnyminerZ 

Played a bit with the `glocaltokens` package and my best guess is my issue (see [here](https://github.com/leikoilja/ha-google-home/issues/91)) spans from my Nest Wifi router, for which the `local_auth_token` is in a slightly different format (switched a few characters in the tokens below, but format is the same):

> item.device_name: Nest Wifi router
item.hardware: model: "MISTRAL"
item.local_auth_token: CtACAE4ACAALAAAEgAAgdaXAO4iqhqCe6mXqbliGQzz1AjnZhcbsEb8qVGKCIn0AEAAgaw0EUW+MPaJS5z4T7PALYZxNi2kGw++Z+vmdE6oLF/4AfgAgZgetRcBQPHVie3KuSuA8PuU1p/kpG5l8AMkkc5WWPBoAEKlwL+zPgRwApr/7rZkuKd8JidWfh1zRjLIelrkDSnsl7NwWzYNdg/gZH4F0WnCG/srFRLcFQljqyeeAwIrWjFd2tGjCAVT5pOIKUfLIZLwk7ZIvpDrLjM6DnhIMSZnDZdWChNPxn5SKGhAF7MX7RnKbFEM0dgZgOshLIgL4vw==

All of my other Google / cast-enabled devices seem to follow a consistent format:

> item.device_name: Kitchen Mini
item.hardware: model: "Google Home Mini"
item.local_auth_token: fMv4w4cCAAAAAAAAjPgBgsftz0E2CrdojudnN9NCmV+/Qzj5iYzos9NtLt/t2aIWsXQjupO/FNMMjLcyzWNIiKDGP5OA5+qBshhtUg1kfPlF

> item.device_name: Living Room TV
item.hardware: model: "BRAVIA 4K UR2"
item.local_auth_token: 3iN/1BwAAAAAAAAAAKqcwQy7LOXORfFukFcFWPo9raVtqZ4gvCa4meTFJ844eTJZM/ArDOErPUn8UK/QNDHuBaz+pW1QIKYYBAM/iHydtDw=

Don't hesitate if I can help in any other way!

**Comment by leikoilja** [comment]
Thank you, @philippefs35 for spotting it. We have now merged the fix(#45) for the bug you were having, so after a new release of `glocaltokens` comes out it will not recognize non google home devices that have a token of a different format than expected. :)
