### ISSUE TITLE
how to disable your master token

### ISSUE THREAD

**Issue by HenkTillaart** [leikoilja/glocaltokens#506]
**Describe the bug**
Run the docker to make a master token 3 times. I have got now 3 master tokens. How to remove 2 of master tokens?

**Comment by leikoilja** [comment]
this is not controlled from `glocaltokens` and if there is any way to remove these master token - that needs to be explored on Google side. Are you sure the previous 2 tokens are not automatically invalidates when you get a new token?

**Comment by KapJI** [comment]
They are not invalidated for a long time. I guess you can use logout everywhere feature or revoke app password to invalidate old tokens.

**Comment by HenkTillaart** [comment]
The "old" master tokens are still working and valid. I removed the app password en generate a new one. Still the "old" master tokens are working. to be continued...

**Comment by KneelStar** [comment]
does anyone know how long the master token lasts? what is a long time?
