### ISSUE TITLE
Arm and grpcio, grpcio-tools and jq 

### ISSUE THREAD

**Issue by DurgNomis-drol** [leikoilja/glocaltokens#6]
**Describe the bug**
I have been trying to make an custom component that generate sensors form timers and alarms, a little different then the custom component you have made. But i ran into this problem with the docker version of homeassistant, because it runs on an alpine image, grpcio and grpcio-tools dosent install corretly if you dont install them manually in the docker image, and add "apk add gcc g++ linux-headers" before doing so. My docker runs on a raspberry pi 4, so i dont know if its only a Arm issue.

Is there anyway we can solve this. 

Jq doesnt work either on Arm/Raspberry pi 4
I have not uploaded my component to github yet, but i plan to as soon as you either merge my pull request on jq or find another way to get rid of jq. 

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by leikoilja** [comment]
Hey, @DurgNomis-drol.
Thanks for raising the issue and PR. I have got stuck in the same problem with `grpcio` and `grpcio-tools` not working correctly on `arm`, that hinders me from releasing it as a working component for Home Assistent (WIP repo here: https://github.com/leikoilja/ha-glocaltokens). Let me know what are you working on as a component, maybe we can collaborate and make it work. Haven't had time to look at `grpcio` and `grpcio-tools` working on `arm` yet

**Comment by DurgNomis-drol** [comment]
Here is what i am working on, [https://github.com/DurgNomis-drol/ha-google_home_local](https://github.com/DurgNomis-drol/ha-google_home_local) i have updated it to use the new version of glocaltokens(0.1.3) and it works.

I think it would be best if we could make only one componet in the end(Better for all users), and i can see you have already done a lot of work on yours to make it pretty and configural through the UI. What do you think?

On the problem with grpcio and grpcio-tools, as of now i dont now if its a problem with how homeassistant generates there docker images from alpine or if it is a problem grpcio and grpcio-tools itself with alpine on arm. 

Im not an programmer, so for me learning these tings is a bit of trial and error and a lot of research and lost hair

**Comment by leikoilja** [comment]
I think it would be great if we would merge those two repos into one, which is better taken care of by more ppl(seems like there are at least two of us interested in this now).

Unfortunately, I don't have much time to look into that this week due to my day job, but will be able to spend some time from next week onwards. 
If you feel for a merge, I am very much open for PRs to merge the work together with https://github.com/leikoilja/ha-glocaltokens. I have started adding `ha-glocltokens` wheels to HA custom components(See https://github.com/home-assistant/wheels-custom-integrations/pull/251) so once it's merged we need to make sure it's working and then can release it to HACS . 
I see that you have started implementing some nice sensors and services, I am open to move some of those into the `ha-glocltokens` repo and make you a collaborator in the repo, so we could both maintain it. Would be nice to have both `glocaltokens` and `ha-glocaltokens` living close-by.

**Comment by DurgNomis-drol** [comment]
Im open for a merge into your integration. If you make me a maintainer, i will start duplicating each sensor in ha-glocaltokens. 

I have created an delete service. Unfortunately there is not a create/add possibility 

But i have another strange problem with gpsoauth. When i run a simpel script to retrieve devices from my username and app-password google devices it works fine. But if i try the using my app-password both in mine or yours integration it fails and says "Request had invalid authentication credentials" or in yours it just fails in the GUI saying incorrect username/password. Do you have any idea of why there is a different? i have tried specifying a android id i knows work.

**Comment by leikoilja** [comment]
Sorry, @DurgNomis-drol, I start losing track of our conversations. 
Will keep this issue open for now to see if the pinning of `grpcio` will fit the wheel building in HA images.
Please open a new issue in https://github.com/leikoilja/ha-glocaltokens if the authentication fails for you, so we could take it from there.
Also, I will add a bit of info about the contribution to https://github.com/leikoilja/ha-glocaltokens in the next few days and then invite you as a collaborator for that repo.

**Comment by DurgNomis-drol** [comment]
Sorry, i have made a separate bug report for that issue. 

I have made good progress merging my code into your integration, but there are a couple of things that we have to finde af way to handle. I will be uploading my version of this so that you can test it and vi can discuss what and how each thing is best implemented in the final version.

**Comment by leikoilja** [comment]
Sounds great! I suggest you create a fork of `ha-glocaltokens`and create there a new branch for your merge with all the proposed changes. Then we can work on that nicely to integrate both things together, keeping the communication within github, close to the source

**Comment by DurgNomis-drol** [comment]
Sure, i will do that. I'm probably gonna take a little break from it, so I will do it in a couple of days

My suggestion would be to add each feature/bug as you have done in your projects, so we can keep track of everything separately.

**Comment by leikoilja** [comment]
Added another [issue](https://github.com/leikoilja/glocaltokens/issues/11) to keep all the discussion about grpcio there.
