### ISSUE TITLE
Remove old branches

### ISSUE THREAD

**Issue by KapJI** [leikoilja/glocaltokens#81]
**Describe the bug**
This repo has many stale branches which need to be removed.
<img width="1267" alt="Screenshot 2021-04-14 at 13 13 20" src="https://user-images.githubusercontent.com/3767331/114708396-31cf0880-9d23-11eb-8367-432782efe364.png">

Probably this setting is not enabled in this repo: https://docs.github.com/en/github/administering-a-repository/managing-the-automatic-deletion-of-branches

**Comment by leikoilja** [comment]
Hmmm, but it is 
![image](https://user-images.githubusercontent.com/10655107/114708805-203e2e80-9d2c-11eb-8099-c0ceb05cf219.png)

I'm wondering if github is behaving here...

**Comment by leikoilja** [comment]
If i try removing them manually it says 
![image](https://user-images.githubusercontent.com/10655107/114708984-54195400-9d2c-11eb-975b-6a9af5e72512.png)

**Comment by KapJI** [comment]
Maybe there is some branch protection rule set?
https://docs.github.com/en/enterprise-server@2.21/github/administering-a-repository/managing-a-branch-protection-rule

**Comment by leikoilja** [comment]
haha, yep!

**Comment by KapJI** [comment]
Also it's nice to enable `linear history` and `require linting job to pass` there 🙂

**Comment by leikoilja** [comment]
also just discovered and fixed it, wanted to let you know but saw your comment. Should be good now, thanks for bringing it up for attention, it was indeed a branch protection rule that was badly set. Now it's the same as in `ha-google-home` with encourced checl
