### ISSUE TITLE
Setup automatic release flow

### ISSUE THREAD

**Issue by KapJI** [leikoilja/glocaltokens#88]
The plan is to setup action which runs when release in published which will build and upload new package to PyPI. Like here:
https://nicholasnadeau.me/post/2020/8/one-version-to-rule-them-all-keeping-your-python-package-version-number-in-sync-with-git-and-poetry/

The version should be inferred automatically from the latest tag.

@leikoilja can you add `PYPI_TOKEN` to github secrets? Set scope to only this project: https://pypi.org/help/#apitoken

**Comment by leikoilja** [comment]
Just added `repository secret` called `PYPI_TOKEN` ✅

**Comment by KapJI** [comment]
Yay! It works 😀
https://github.com/leikoilja/glocaltokens/runs/2379078382

**Comment by leikoilja** [comment]
THIS is incredible! 😍  Big thanks
